package com.study.springboot.mapper;


import com.study.springboot.entity.EmpExample;
import com.study.springboot.entity.Memorials;
import com.study.springboot.entity.MemorialsExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface MemorialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 21 16:06:21 CST 2022
     */
    int countByExample(MemorialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 21 16:06:21 CST 2022
     */
    int deleteByExample(MemorialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 21 16:06:21 CST 2022
     */
    int deleteByPrimaryKey(Integer memorialsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 21 16:06:21 CST 2022
     */
    int insert(Memorials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 21 16:06:21 CST 2022
     */
    int insertSelective(Memorials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 21 16:06:21 CST 2022
     */
    List<Memorials> selectByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 21 16:06:21 CST 2022
     */
    Memorials selectByPrimaryKey(Integer memorialsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 21 16:06:21 CST 2022
     */
    int updateByExampleSelective(@Param("record") Memorials record, @Param("example") MemorialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 21 16:06:21 CST 2022
     */
    int updateByExample(@Param("record") Memorials record, @Param("example") MemorialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 21 16:06:21 CST 2022
     */
    int updateByPrimaryKeySelective(Memorials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 21 16:06:21 CST 2022
     */
    int updateByPrimaryKey(Memorials record);

    List<Memorials> getAllMemorials();

    List<Memorials> getAllMemorialsById(String empID);

    Memorials getMemorialsDetailById(Integer memorialsId);

    int insertMemorials(@Param("memorialsEmp") Integer empID,@Param("memorialsTitle") String memorialsTitle,@Param("memorialsContent") String memorialsContentDigest,@Param("memorialsCreateTime") String qizouTime,@Param("memorialsImgPath") String imageName);

    int updateMemorialsStatusToRead(Integer memorialsId);

    int updateMemorialsFeedBack(@Param("memorialsId")Integer memorialsId ,@Param("feedbackContent")String feedbackContent,@Param("feedbackTime")String feedTime);

    List<Memorials> getAllMemorialsDetailBySearch(@Param("mTitle") String mTitle,@Param("eId") String eId, @Param("mStatus") String[] mStatus,@Param("empId") String empID);

}